name: countdown
description: A countdown tracker app

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.0.2
  path_provider: ^1.6.11
  uuid: ^2.2.0
  process_run: ^0.10.10+2
  flutter_local_notifications: ^3.0.2
  timezone: ^0.5.9
  flutter_native_timezone: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "assets/icon/countdown_icon.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
