name: countdown
description: A countdown tracker app

publish_to: "none"

version: 1.1.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  package_info: ^0.4.3+2
  cupertino_icons: ^0.1.3
  provider: ^4.0.2
  path_provider: ^1.6.11
  uuid: ^2.2.0
  process_run: ^0.10.10+2
  flutter_local_notifications: ^3.0.2
  timezone: ^0.5.9
  flutter_native_timezone: ^1.0.4
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4
  mockito: ^4.1.3
  http_server: ^0.9.8+3

# config section for flutter_launcher_icons
# Generate via `flutter pub get && flutter pub run flutter_launcher_icons:main`
flutter_icons:
  image_path: "assets/app_icon_1024x1024.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon_120x120.png
